name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  json_annotation: ^4.9.0
  build_runner: ^2.5.4
  cupertino_http: ^2.2.0
  fetch_client: ^1.1.4
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  flutter_spinkit: ^5.2.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
