swagger: "2.0"
info:
  title: Versionary Collab API
  version: 1.0.0
paths:
  /users:
    post:
      summary: Cadastro de usuário
      operationId: createUser
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              usuario:
                type: string
              nome:
                type: string
              email:
                type: string
              senha:
                type: string
      responses:
        '201':
          description: Usuário cadastrado com sucesso
        '400':
          description: Item faltando no payload
      x-google-backend:
        address: https://user-service-g7q3p545qa-sa.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS