name: Atualização microsserviços na GCP

on:
  push:
    branches: [ "main" ]

env:
  GAR_REPOSITORY: "versionary-collab" 

jobs:
  deploy-services:
    name: Deploy dos microsserviços
    runs-on: ubuntu-latest
    environment: environment
    
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      matrix:
        service-name: [user-service, post-service]
        # notification-service]
        include:
          - service-name: user-service
            build-context: ./backend/user-service
          - service-name: post-service
            build-context: ./backend/post-service
          # - service-name: notification-service
          #   build-context: ./backend/notification-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Autenticação Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}

      - name: 'Buildx Docker'
        uses: docker/setup-buildx-action@v3
      - name: 'Build e push da imagem'
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.build-context }} 
          push: true
          run: echo "${{ vars.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}/${{ matrix.service-name }}:${{ github.sha }}"
          tags: ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ matrix.service-name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 'Deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ matrix.service-name }} 
          region: ${{ vars.REGION }} 
          image: ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ matrix.service-name }}:${{ github.sha }}
          flags: '--allow-unauthenticated'
